<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
    <BaseOutputPath>../build/SQLCipherED</BaseOutputPath>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>SQLCipher DB Decrypt</Title>
    <AssemblyVersion>0.3.3</AssemblyVersion>
    <FileVersion>0.3.3</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Version>$(AssemblyVersion)</Version>
    <Description>SQLCipher DB decrypt pure C# implementation</Description>
    <PackageProjectUrl>https://github.com/mIwr/SQLCipherED</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/mIwr/SQLCipherED</RepositoryUrl>
    <RepositoryType></RepositoryType>
    <AnalysisLevel>6.0</AnalysisLevel>
    <IsPublishable>False</IsPublishable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>mIwr</Authors>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
